### ISSUE TITLE
Quaver sets pause timeout twice when it is moved to a stage channel while playing

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#106]
**Describe the bug**
Quaver sets pause timeout twice when it is moved to an empty stage channel **while playing a track.**

Reproducible through Stage channels only.
Moving Quaver to a voice channel sets pause timeout only once which is intended.

**To Reproduce**
1. Make sure 24/7 is off.
2. Join a Voice or Stage channel.
3. Play any track with Quaver.
> For this step, something similar should be shown on console
```
[G 906471497231630336 | U 250934589621665793] Processing command play
[G 906471497231630336 | U 250934589621665793] Executing command play
[G 906471497231630336] Starting track
```

4. Move Quaver to a Stage channel. 
> See error

> This is what's shown on discord
```
There's nobody here. I'll leave in 5 minutes.
Rejoin to resume your session.

There's nobody here. I'll leave in 5 minutes.
Rejoin to resume your session.
```

> This should be shown on console
```
[G undefined] Setting pause timeout
[G undefined] Setting pause timeout
```
This issue does not cause a crash, so no `error.log`.

**Expected behavior**
Quaver should only set a pause timeout once when it is moved to a stage channel while it is playing.

**Additonal context**
Directly related to #107

**Comment by zapteryx** [comment]
does the bot also say disconnected from inactivity twice?

**Comment by Xayanide** [comment]
> does the bot also say disconnected from inactivity twice?

Tested that just now, it disconnects from inactivity only once.
```
[Quaver] Connected to Discord! Logged in as ThatKid#6969.
[Quaver] Running version 3.3.0-next.2. For help, see https://github.com/ZapSquared/Quaver/issues.
[Quaver] Connected to Lavalink!
[G 906471497231630336 | U 250934589621665793] Processing command play
[G 906471497231630336 | U 250934589621665793] Executing command play
[G 906471497231630336] Starting track
[G 906471497231630336] Setting pause timeout
[G 906471497231630336] Setting pause timeout
[G 906471497231630336] Disconnecting (inactivity)
```
