### ISSUE TITLE
A better error message for the play command.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#115]
**Describe the solution you'd like**
Instead of showing 'There was an error while handling the command.' when something wrong happened with the play commmand, show a more descriptive reason as to why it didn't play.

e.g., The following track cannot be played due to an age verification.

**Additional context**
https://discord.com/channels/906471497231630336/920107978760261663/942390457726566400

**Comment by zapteryx** [comment]
did the best I could with b1f333c0b2bcdb8ee5351e3538f29e8dc8126111
