### ISSUE TITLE
Quaver crashes on sending a message with insufficient text channel permissions

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#130]
**Describe the bug**
Quaver crashes when it attempts to send a message with insufficient permissions on voiceStateUpdate

**Affected versions**
What versions of Quaver are affected by this bug? (e.g. all versions before 3.0.1, 2.5.1 to 2.6.3, all versions from 1.2.0)
Prevalent around 2.7.0 to 3.3.0

**To reproduce**
1. At first, give Quaver Administrator permissions.
2. Play a track on any channel.
3. Remove Quaver's Administrator permissions while it is in the channel. Make sure nothing is overriding it, and it shouldn't be able to send messages on a text channel.
4. We will trigger a locale string for Quaver to send a message to a text channel it can't send to.
> In this case we will make it trigger and say the `MUSIC_FORCED` string.
5. Do /disconnect or manually disconnect it by right clicking and clicking disconnect.
6. Quaver crashes
7.  See error
> error.log
```js
unhandledRejection
Missing Permissions
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async TextChannel.send (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:175:15)
    at async Client.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\main.js:520:4)
```
> Console after doing the the reprduction steps
```js
$ node main.js
[Quaver] Connected to Discord! Logged in as ThatKid#6969.
[Quaver] Running version 3.3.0. For help, see https://github.com/ZapSquared/Quaver/issues.     
[Quaver] Connected to Lavalink!
[G 906471497231630336 | U 250934589621665793] Processing command play
[G 906471497231630336 | U 250934589621665793] Executing command play
[G 906471497231630336] Starting track
[G 906471497231630336] Setting pause timeout
[Quaver] Shutting down...
[Quaver] Disconnecting from all guilds...
[Quaver] Logging additional output to error.log.
```

**Expected behavior**
Quaver shouldn't attempt to do any actions on channels it doesn't have permissions for. Proper permission checks on affect areas will do.

**Comment by zapteryx** [comment]
hm. i may want to rewrite this

**Comment by Xayanide** [comment]
If Quaver voiceStateUpdates and involves sending a message to a particular channel it doesn't have permission to send into, it will throw an error or perhaps crash. I think in every `send()` needs to have a check before that.

**Comment by Xayanide** [comment]
Fixed by 
https://github.com/ZapSquared/Quaver/commit/029b18cfd281233f7f36cda6cceead355742ac8e and https://github.com/ZapSquared/Quaver/commit/e15ab0048a0c6fe3c1a85124f02b0112557f0ac2
