### ISSUE TITLE
Usage of reconnects option for Lavalink

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#131]
**Is your feature request related to a problem? Please describe.**
Quaver never actually attempts to reconnect back when it gets disconnected and has to be restarted to reconnect.

**Describe the solution you'd like**
Automatically reconnect for x amount of times set by the bot owner if Lavalink disconnects from Quaver

**Feature**
An option in settings that allows Quaver to attempt to reconnect back to Lavalink in x amount of `tries` and `delay`, the default values' are up to you.

**Comment by zapteryx** [comment]
i'll look into this and see if it's actually possible with the library we're currently using; seems interesting
