### ISSUE TITLE
When Quaver reaches a certain uptime, its status disappears.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#137]
**Describe the bug**
When Quaver stays up for longer than a week or so, it's status with the version string disappears.

**Affected versions**
What versions of Quaver are affected by this bug? (e.g. all versions before 3.0.1, 2.5.1 to 2.6.3, all versions from 1.2.0)
This was most likely overlooked since the early versions, I say roughly 2.8.0 above.

**To reproduce**
1. Run Quaver.
2. Let it run for over a week or so.

**Expected behavior**
Quaver's status should remain intact.

**Additional context**
Issue most likely related to discord's end.

**Comment by zapteryx** [comment]
indeed something to do with discord as the status appears on some guilds. i could fix this by periodically sending a presence update though.
