### ISSUE TITLE
Quaver does not shut down after the first SIGINT signal.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#138]
**Describe the bug**

**This bug was overlooked since** `2.5.0.next.1`
Applies to both `SIGINT` (CTRL+C) and `EOT` (CTRL+D)
Not sure if this was intended, this seemed like a termination confirmation ngl.

Doing CTRL+C in the terminal does not terminate Quaver, doesn't immediately show the "Shutting down." prompt. Readline commands no longer work from there.

User has to press CTRL+C twice to shut down Quaver.
Similar behaviour for `CTRL+D`

**Affected versions**
What versions of Quaver are affected by this bug? (e.g. all versions before 3.0.1, 2.5.1 to 2.6.3, all versions from 1.2.0)

All versions after `2.5.0.next.1`

**To reproduce**
1. Run Quaver, `node main.js`
2. Press `CTRL+C`
3. Readline commands no longer work.
4. Ping the bot, it is still operating. `/ping`
5. Press the `CTRL+C` again.
6. See error
> Quaver now shut downs after pressing `CTRL+C` the second time.

**Expected behavior**
Doing SIGINT or CTRL+C should immediately shut down or terminate Quaver gracefully.

**Comment by zapteryx** [comment]
does it function without the double ctrl+c prior to that commit?

**Comment by Xayanide** [comment]
> does it function without the double ctrl+c prior to that commit?

yes. as only 3.3.0 is affected by this

**Comment by Xayanide** [comment]
Update: This is the commit that started it 

https://github.com/ZapSquared/Quaver/commit/1d152097f56634fda13c853d93c9ac390555fff0

**Comment by Xayanide** [comment]
Most minimal code that can reproduce the issue.
```js
const { Client } = require('discord.js');
const { token, defaultLocale } = require('./settings.json');
const { getLocale } = require('./functions.js');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});
rl.on('line', line => {
    switch (line.split(' ')[0]) {
        case 'exit':
            process.exit();
            break;
        default:
            console.log(getLocale(defaultLocale, 'CMDLINE_HELP'));
            break;
    }
});

const bot = new Client({ intents: [] });
bot.login(token);
```

Removing `bot.login(token)` resolves the issue, meaning the bot has to not login.
