### ISSUE TITLE
Quaver can crash with DiscordAPIError: Unknown Message

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#167]
**Describe the bug**
What isn't working as intended, and what does it affect?
Everything works as intended, affects functionality.

Only works with slash commands
This bug is not that important to fix, but it's up to you if you want spend the time to fix it.

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
All versions

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Use a command that can become busy and takes a while to load, that uses `reply({`, even effective with `deferReply({`
2. Prepare to aim, at the right corner of your chat box, anticipating for a message.
3. We'll use the play command since it can become busy.
4. As you play a track, wait for the exact time for the message to pop-up.
5. Hold `SHIFT` and left click the trash button of the recently sent message by Quaver
Must be done in Quick succession.

**Expected behavior**
What is expected to happen?
A check in interactionCreate that returns if the interaction message no longer exists (probably needs more conditions).

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Since Quaver is still busy and there is no check for the reproduced issue, it is still doing its activities while the message that it sent no longer exists, therefore the crash `DiscordAPIError: Unknown Message`.

**Comment by zapteryx** [comment]
you sneaky little-

**Comment by Xayanide** [comment]
Additionally, once this issue is reproduced, Quaver gets stuck at the `shuttingDown` asynchronous function. The only way to shut down Quaver from there is to end the process.
