### ISSUE TITLE
Locale that has missing strings makes Quaver's commands that use those strings to not work.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#213]
**Describe the bug**
What isn't working as intended, and what does it affect?
Locale
Affects functionality.

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
`3.0.0^`

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Run Quaver.
2. Type and enter `/locale` command, use a locale that has incomplete strings.

**Expected behavior**
What is expected to happen?

Ways of implementation I found, there could be more:
1. Strings that are complete should stay at its translated state. Strings that are incomplete, however, should stay at en-US so commands will be usable.

2. Other faster work-around for this would be to not allow incompleted locales to be used all-together and instead use other complete locales like en-US entirely.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.

For a highly likely example, if a locale is at 0% and a user sets it as their locale, every command will no longer work since there is not a single string for that locale set yet.

If a command tries to send a string that it uses that doesn't even exist yet, shows this.
```
The application did not respond
```

**Comment by zapteryx** [comment]
not intended behavior. the intended behavior is indeed for Quaver to send a message with the en locale, but it seems to be bugged.

**Comment by zapteryx** [comment]
i seem to have accidentally fixed this in one of the newer versions (tested on next.56), please re-open the issue if it persists
