### ISSUE TITLE
Does not leave when left alone in a voice channel while playing a track.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#25]
**Describe the bug**
Quaver does not disconnect when left alone in a voice channel while playing a track.

**To Reproduce**
1. Go to a voice channel.
2. Play a lengthy track through /play. E.g., play a stream whose length is indefinite.
3. For instance, I forgot to disconnect the bot and just left the channel.
4. Quaver stays in the channel playing the track until it finishes. 

If the track is a stream, which does not signify its length and when it ends, Quaver still stays in the channel until that track finishes even when it is left alone, wasting resources.

**Expected behavior**
Quaver should automatically disconnect after being left alone in a channel for a determined amount of time. Even if it is currently playing a track.

**Comment by zapteryx** [comment]
thanks! 6d61ba132ed07766b2011fdc25702d819286810c fixes the bug with not leaving automatically after a track when nobody is in the vc, and i'll find a solution to not leaving when people leave mid-way.
