### ISSUE TITLE
There was an error while handling the command.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#39]
**Describe the bug**
Quaver gave "There was an error while handling the command." when using play command to connect to Stage channels.

Permission issue.

Reproducible if this condition is met:

- Quaver do not have Administrator permission in any of its roles or on itself.

**To Reproduce**
1. It does not matter whether all permissions that were directed at Quaver are ticked
or all permissions directed at Quaver are unticked.
Just as long as the Administrator permission is unticked it is producible.
2. Click on a Stage channel.
3. Use the play command as usual.
4. See error "There was an error while handling the command."
5. On my instance, there is a [Symbol(code)]: 'BITFIELD_INVALID' error on the console.

**Expected behavior**
A track should be playing and added to the queue as expected, just like on voice channels.
Quaver should be able to join stage channels without the need of the Administrator permission.

**Comment by zapteryx** [comment]
how odd. I'll check this again later
