### ISSUE TITLE
Quaver still thinks it's in a channel when it gets manually disconnected.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#43]
**Describe the bug**
Quaver still thinks it is still in a voice channel if you manually Disconnect it through Discord.

**To Reproduce**
1. Play any track. Use the bot as usual. Let it connect to the voice or stage channel.
2. Right click on Quaver on the channel it is in.
3. Click on Disconnect
4. Now use any command that has the functionality that it will not execute the command if the user is not in the same voice channel as Quaver.
5. After executing those kind of commands e.g., /play /playing /skip you will see "You need to be in my voice channel."

**Expected behavior**
When manually disconnecting Quaver, Quaver should disconnect as if it were disconnected using the /disconnect command.
Quaver shouldn't keep sessions if it is manually disconnected through Discord.

**Comment by zapteryx** [comment]
can you verify that this issue only persists for disconnecting? what happens if you move Quaver? does it also function oddly, i.e. you need to be in my vc?

**Comment by Xayanide** [comment]
> can you verify that this issue only persists for disconnecting? what happens if you move Quaver? does it also function oddly, i.e. you need to be in my vc?

Issue only persists for disconnecting. Moving the bot to another channel, still works as usual.
