### ISSUE TITLE
Quaver crashes when it attempts to send a message with missing permissions.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#68]
**Describe the bug**
Quaver crashes when it attempts to send a message to a text channel it can't see.

**To Reproduce**
> To reproduce a crash faster, we will do it this way since it is faster.

1. Give Quaver Administrator permissions or any other roles that overrides it, just as long as it can see messages.

> We will attempt to make Quaver send a message on a text channel it can't see. So we want to trigger Quaver to send "MUSIC_FORCED_STAGE" to the text channel it is currently sending at.

2. Play with Quaver on a stage channel with these permissions disabled [Speak, View Channel, Request to speak]
3. Make sure that Quaver is playing on a text channel with these permissions disabled [View channel] [Send message]

> On step one, Quaver has Administrator permissions so it should be able to join, speak, send a message to a channel with those permissions set as that since Administrator overrides all of those.

3. Move Quaver to another stage channel or voice channel.
4. Remove Quaver's Administrator permission.

> So with this, Quaver shouldn't be able to see the channel at all, Quaver should no longer have the ability to become a stage moderator this way.

5. Move Quaver back to the previous stage channel from step 2.

> Quaver no longer has Administrator permissions, thus not being able to see, send to a text channel, cannot speak or become a stage moderator anymore.
> Through this, will trigger MUSIC_FORCED_STAGE

> Quaver attempts to send this to the text channel, but it cannot see the text channel because it no longer has access to it since we removed Administrator permission from step 4.

6. Quaver crashes.
7. See error
```
unhandledRejection
Missing Access
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/t3/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/t3/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/runner/t3/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15)
```
> or this which also mean the same thing.
```
unhandledRejection
Missing Permissions
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15)
```

**Expected behavior**
Quaver shouldn't attempt on sending a message to the text channel it can't see
Quaver should have proper permission checks on place for this

**Comment by zapteryx** [comment]
is this issue specific to stage?

**Comment by Xayanide** [comment]
> is this issue specific to stage?
yes

**Comment by zapteryx** [comment]
> > is this issue specific to stage?
> 
> yes, basing on the reproduction steps given above, MUSIC_FORCED_STAGE was used to reproduce the crash which is related to a Stage channel. There may be other things that can produce the same outcome using similar steps.

you reckon you could try to replicate it for anything else? this way i can fix them in one go
