### ISSUE TITLE
A probability that Quaver fails to show queue after using shuffle.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#69]
**Describe the bug**
There is a probability for Quaver to fail to show the queue after using shuffle.

# Not reproducible on Quaver 3.1.0-next.1 and below.
**To Reproduce**
1. Play more than 1 track or a playlist with a lot of tracks.
2. Use the shuffle command for x amount of times in a row.
3. Use the queue command.
4. There is a probability that you will meet this ephemeral
```
There was an error while handling the command.
```

**Expected behavior**
Quaver should show the queue after using shuffle (multiple times in a row).

**Comment by zapteryx** [comment]
yea i was making a huge gamble by doing what i did, i'll revert it for now
