### ISSUE TITLE
Quaver doesn't list one of the missing strings when checking for locale completion

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#75]
**Describe the bug**
Quaver doesn't list one (or some) of the missing strings of an outdated locale when checking for its completion

**To Reproduce**
> For this one, 247 got added, that means all locales except en-US are outdated. So we'll use an outdated locale with missing 247 strings.
1. Use Quaver's locale command on a locale with missing strings for 247.
2. Quaver shows 5 missing strings.
```
CMD_247_OPTION_ENABLED
CMD_247_ENABLED
CMD_247_DISABLED
CMD_247_NOTE
CMD_DISCONNECT_247_ENABLED
```

3. If we look at en-US which is updated, it had `CMD_247_DESCRIPTION`. 
4. The outdated locale that was selected is also missing that string, but Quaver did not list it.

**Expected behavior**
Proper locale completion check for Quaver.
Quaver should correctly list all the missing strings of an outdated locale.

**Comment by zapteryx** [comment]
additional info, function is working fine, just when displaying.
