### ISSUE TITLE
Quaver doesn't work well when removing position 0 from a queue.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#93]
**Describe the bug**
Quaver doesn't work well when removing position `0` from a queue.

**To Reproduce**
1. Play a track with Quaver
2. Add something to the queue after that.
3. Try removing position 0, e.g., `/remove position: 0`
> On discord.

```There was an error while handling the command.```

**Expected behavior**
```Please specify a valid index.``` is supposed to pop up, not the error.

**Additional context**
Not reproducible on `3.1.0` and below.

**Comment by zapteryx** [comment]
re-run deploy-commands.js
