### ISSUE TITLE
Quaver's volume can be set with negative integers.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#94]
**Describe the bug**
Quaver's volume using the volume command can be set with negative integers which is not supposed to happen, also beyond `-200%` as well. Setting positive 200% is working ok and doesn't go above it.

With the presence of this bug, the string `CMD_VOLUME_NOT_IN_RANGE` is unused for the volume command.

**To Reproduce**
1. Play a track on Quaver on a voice or stage channel.
2. Use the volume command, set it to below 0% e.g., `-999999%`
3. See error.
`Volume adjusted to -999999%`

**Expected behavior**
Quaver isn't supposed to set volume with negative integers, implement proper checks for it, so if negative integers are being set it outputs the `CMD_VOLUME_NOT_IN_RANGE` string.

**Additional context**
Not reproducible on `3.1.0` and below.

**Comment by zapteryx** [comment]
re-run deploy-commands.js
