### ISSUE TITLE
Quaver doesn't accept 0 as a volume.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#96]
**Describe the bug**
Quaver doesn't accept 0 as a its volume.

**To Reproduce**
1. Play a track with Quaver
2. Attempt to set volume to 0, e.g.,  `/volume newvolume: 0`
3. See error.
```
Input an integer from 1 to 1000
```

**Expected behavior**
> String name [`CMD_VOLUME_NOT_IN_RANGE`](https://github.com/ZapSquared/Quaver/blob/e0bf59342ed10ace10bbded91bc6a938932e5d60/locales/en-US.json#L149) explicitly states "0% to 200%" so Quaver should also be able to set its volume to 0%

**Comment by zapteryx** [comment]
re-run deploy-commands.js to fix
